# Generated by Django 4.2.13 on 2024-05-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('sleepy_count', models.PositiveIntegerField(default=0)),
                ('gaze_left_count', models.PositiveIntegerField(default=0)),
                ('gaze_right_count', models.PositiveIntegerField(default=0)),
                ('gaze_down_count', models.PositiveIntegerField(default=0)),
                ('gaze_down_long_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
