# Generated by Django 4.2.13 on 2024-05-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='pose',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
